# Generated by Django 3.2.7 on 2021-09-14 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='firstname',
            new_name='document_name',
        ),
        migrations.RenameField(
            model_name='info',
            old_name='lastname',
            new_name='user_id',
        ),
    ]
