# Generated by Django 3.2.7 on 2021-09-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp', '0002_auto_20210914_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='ip_address',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='port',
            field=models.IntegerField(null=True),
        ),
    ]
